Connect Python with MySQL

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mysql.connector


db = mysql.connector.connect(host = "localhost",
                            username = "root",
                            password = "123456789",
                            database = "ecommerce")

cur = db.cursor()

List all unique cities where customers are located.

In [6]:
query="""select distinct customer_city from customers"""
cur.execute(query)
data=cur.fetchall()
df=pd.DataFrame(data)
df.head()

                       0
0                 franca
1  sao bernardo do campo
2              sao paulo
3        mogi das cruzes
4               campinas

Count the number of orders placed in 2017.

In [7]:
query="""select count(order_id) from orders where year(order_purchase_timestamp) = 2017"""
cur.execute(query)
data=cur.fetchall()
df=pd.DataFrame(data)
print(f" The count of order is {df[0][0]}")

 The count of order is 45101

Find the total sales per category.

In [8]:
query = """ SELECT 
CONCAT(
    UPPER(LEFT(t.product_category_name_english,1)),
    LOWER(SUBSTRING(t.product_category_name_english,2))
) as Cateogry,
round(sum(payment_value),1) as Total_sales
from category_translation t
join products p
on t.product_category_name=p.product_category_name
join order_items o
on p.product_id=o.product_id
join order_payments op
on op.order_id=o.order_id
group by t.product_category_name_english
order by Total_sales desc
"""

cur.execute(query)

data = cur.fetchall()

df = pd.DataFrame(data, columns = ["Category", "Total_sales"])
df

                     Category  Total_sales
0              Bed_bath_table    1712553.7
1               Health_beauty    1657373.1
2       Computers_accessories    1585330.4
3             Furniture_decor    1430176.4
4               Watches_gifts    1429216.7
..                        ...          ...
66                    Flowers       2213.0
67             Home_comfort_2       1710.5
68          Cds_dvds_musicals       1199.4
69  Fashion_childrens_clothes        785.7
70      Security_and_services        324.5

[71 rows x 2 columns]

Calculate the percentage of orders paid by each payment type.

In [15]:
query="""select round((sum(case when payment_type="boleto" then 1 else 0 end)/count(order_id))*100,2) as cash_payment,
round((sum(case when payment_type="credit_card" then 1 else 0 end)/count(order_id))*100 ,2) as credit_card_payment,
round((sum(case when payment_type="voucher" then 1 else 0 end)/count(order_id))*100 ,2) as voucher_payment,
round((sum(case when payment_type="debit_card" then 1 else 0 end)/count(order_id))*100 ,2) as debit_card_payment
from order_payments"""

cur.execute(query)
data=cur.fetchall()
df=pd.DataFrame(data,columns=["credit_card_payment"," cash_payment","voucher_payment","debit_card_payment"])
df.style.hide(axis="index")
df

  credit_card_payment  cash_payment voucher_payment debit_card_payment
0               19.04         73.92            5.56               1.47